filter_orthofinder:
  min_sequences: 5
use_orthofisher: True
orthofisher_hmmer_files:
  - hmms/1001705at2759.hmm
  - hmms/42at3041.hmm
  - hmms/45at3041.hmm
  - hmms/52at3041.hmm
  - hmms/718307-1.fa.mafft.hmm
  - hmms/bena.fa.mafft.hmm
  - hmms/calmodulin.fa.mafft.hmm
