# Based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml
name: testing

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Install dependencies for Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - run: poetry install
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ matrix.python-version }}-cache
        path: |
          tests/test-data/results/
          tests/test-data/.snakemake/conda/
    - name: Run Workflow
      run: poetry run phyloflow --directory tests/test-data results/supermatrix/ascii_tree.txt
    # - name: Testing
    #   run: |
    #     poetry run pytest
